//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P1_Vacunaton_21811039
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string Codigo { get; set; }
        public string contraseña { get; set; }
        public string n_identidad { get; set; }
        public string NombreCompleto { get; set; }
        public string genero { get; set; }
        public string correo { get; set; }
        public string telefono { get; set; }
        public string rol { get; set; }
        public string IdCentroAsistencia { get; set; }
        public string IdVacunas { get; set; }
    
        public virtual CentroAsistencia CentroAsistencia { get; set; }
        public virtual roles roles { get; set; }
        public virtual Vacunas Vacunas { get; set; }
    }
}
