//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P1_Vacunaton_21811039
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacunaXCiudadanos
    {
        public string IdCiudadano { get; set; }
        public int NumeroDosis { get; set; }
        public string IdCentroAsistencia { get; set; }
        public string CodVacuna { get; set; }
        public Nullable<System.DateTime> Fecha_Aplicacion { get; set; }
    
        public virtual Ciudadanos Ciudadanos { get; set; }
        public virtual Vacunas Vacunas { get; set; }
    }
}
